# This minimal config scrape only single log file.
# Primarily used in rpm/deb packaging where promtail service can be started during system init process.
# And too much scraping during init process can overload the complete system.
# https://github.com/grafana/loki/issues/11398

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://localhost:3100/loki/api/v1/push

scrape_configs:

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log

- job_name: system-apps
  static_configs:
  - targets:
      - localhost
    labels:
      job: apps-varlogs
      __path__: /var/log/*/*.log

- job_name: journal
  journal:
    max_age: 24h
    labels:
      job: systemd-journal
      __path__: /var/log/journal
  relabel_configs:
  - source_labels: ['__journal__hostname']
    target_label: host
  - source_labels: ['__journal__systemd_unit']
    target_label: systemd_unit
    regex: '(.+)'
  - source_labels: ['__journal__systemd_user_unit']
    target_label: systemd_user_unit
    regex: '(.+)'
  - source_labels: ['__journal__transport']
    target_label: transport
    regex: '(.+)'
  - source_labels: ['__journal_priority_keyword']
    target_label: severity
    regex: '(.+)'
