---
- name: Ping
  ping:
    data: pong

- name: Check if Raspberry Pi OS
  fail:
    msg: "Playbook runs only on Raspberry Pi OS. Overwrite configurations to run it on another OS."
  when:
    - not (ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Debian')