---

- name: Configure SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: sshd -t -f %s
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^Port"
      line: "Port {{ ssh_new_port }}"
    - regexp: "^X11Forwarding"
      line: "X11Forwarding no"
    - regexp: "^ChallengeResponseAuthentication"
      line: "ChallengeResponseAuthentication no"
    - regexp: "^UsePAM"
      line: "UsePAM no"
    - regexp: "^LoginGraceTime"
      line: "LoginGraceTime 20"
    - regexp: "^MaxAuthTries"
      line: "MaxAuthTries 2"
    - regexp: "^MaxSessions"
      line: "MaxSessions 2"
    - regexp: "^PubkeyAuthentication"
      line: "PubkeyAuthentication yes"
    - regexp: "^MaxStartups"
      line: "MaxStartups 3:50:6"
    - regexp: "^ClientAliveInterval"
      line: "ClientAliveInterval 15"
    - regexp: "^ClientAliveCountMax"
      line: "ClientAliveCountMax 2"
    - regexp: "^AllowUsers"
      line: "AllowUsers {{ ansible_user }}"
  notify: Restart ssh

- name: Restrict file permissions
  file:
    path: /etc/ssh/sshd_config
    mode: 0600

- name: Setup sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: visudo -cf %s
  with_items:
    - regexp: "^{{ ansible_user }} ALL=(ALL)"
      line: "{{ ansible_user }} ALL=(ALL) ALL"
    - regexp: '^Defaults\s+timestamp_timeout'
      line: "Defaults        timestamp_timeout=1"

- name: Disable IPv6 in sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_dict: "{{ sysctl_config }}"
  # ignore errors if IPv6 is already disabled in sysctl
  ignore_errors: yes

- name: Check IPv6 addr
  command:
    cmd: ip -6 addr
  register: ipv6_addr

- name: Debug IPv6 status
  debug:
    msg: "{{ ipv6_addr.stdout_lines }}"

- name: Blacklist IPv6 kernel module
  lineinfile:
    dest: /etc/modprobe.d/blacklist-ipv6.conf
    line: "blacklist ipv6"
    mode: "0644"
    create: yes

- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Disable UFW IPv6
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^IPV6="
    line: "IPV6=no"
    state: present

- name: Allow specific SSH port
  ufw:
    rule: allow
    port: "{{ ssh_new_port }}"
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled

- name: Set default UFW policies
  ufw:
    default: deny

- name: Reload UFW to apply changes
  command: ufw reload

- name: Start UFW service
  systemd:
    name: ufw
    state: started

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Configure fail2ban jail
  copy:
    dest: /etc/fail2ban/jail.local
    content: "{{ fail2ban_jail_local }}"
    mode: "0644"

- name: Configure fail2ban local config
  copy:
    dest: /etc/fail2ban/fail2ban.local
    content: "{{ fail2ban_local_conf }}"

- name: Enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
